/* =====================================================================
   Doodle Spin — Listas de temas
   ---------------------------------------------------------------------
   Há DOIS modos, cada um com a sua própria lista:
     • CATEGORIES → temas amplos, por categoria.
     • CREATIVE   → prompts mais específicos e imaginativos.

   Edite à vontade! Regras simples:
     • Um tema por linha, entre aspas ("..."), terminado com vírgula.
     • Para ADICIONAR: acrescente uma nova linha na lista certa.
     • Para REMOVER: apague (ou comente com //) a linha.
   Depois é só recarregar a página.
   ===================================================================== */

window.DOODLE_CATEGORIES = [
  "Ocean",
  "Beach",
  "Coral Reef",
  "River",
  "Lake",
  "Pond",
  "Waterfall",
  "Swamp",
  "Marsh",
  "Island",
  "Harbor",
  "Lighthouse",
  "Pirate Cove",
  "Forest",
  "Jungle",
  "Rainforest",
  "Woodland",
  "Meadow",
  "Garden",
  "Botanical Garden",
  "Farm",
  "Orchard",
  "Vineyard",
  "Desert",
  "Oasis",
  "Canyon",
  "Mountains",
  "Volcano",
  "Cave",
  "Crystal Cave",
  "Arctic",
  "Antarctica",
  "Savanna",
  "Grasslands",
  "Sky",
  "Clouds",
  "Storm",
  "Rainbow",
  "Sunset",
  "Night Sky",
  "Space",
  "Moon",
  "Mars",
  "Planets",
  "Galaxy",
  "Constellations",
  "Nature",
  "Spring",
  "Summer",
  "Autumn",
  "Winter",
  "Weather",
  "Animals",
  "Pets",
  "Cats",
  "Dogs",
  "Birds",
  "Owls",
  "Butterflies",
  "Bees",
  "Insects",
  "Spiders",
  "Marine Life",
  "Fish",
  "Whales",
  "Sharks",
  "Octopus",
  "Turtles",
  "Reptiles",
  "Dinosaurs",
  "Dragons",
  "Fantasy Creatures",
  "Monsters",
  "Aliens",
  "Robots",
  "Magic",
  "Potions",
  "Spellbooks",
  "Witches",
  "Wizards",
  "Fairies",
  "Mermaids",
  "Unicorns",
  "Phoenix",
  "Mythology",
  "Fairy Tales",
  "Medieval",
  "Pirates",
  "Knights",
  "Castles",
  "Kingdoms",
  "Treasure",
  "Maps",
  "Halloween",
  "Christmas",
  "Easter",
  "Valentine's Day",
  "Carnival",
  "Circus",
  "Festival",
  "Birthday Party",
  "Food",
  "Desserts",
  "Candy",
  "Chocolate",
  "Ice Cream",
  "Cake",
  "Cookies",
  "Bread",
  "Pizza",
  "Pasta",
  "Burgers",
  "Sushi",
  "Fruits",
  "Vegetables",
  "Drinks",
  "Tea",
  "Coffee",
  "Bakery",
  "Kitchen",
  "Restaurant",
  "Tea Party",
  "Flowers",
  "Roses",
  "Sunflowers",
  "Tulips",
  "Cherry Blossoms",
  "Trees",
  "Leaves",
  "Mushrooms",
  "Cactus",
  "Succulents",
  "Vines",
  "Crystals",
  "Gems",
  "Rocks",
  "Shells",
  "Feathers",
  "Jewelry",
  "Crowns",
  "Fashion",
  "Clothing",
  "Shoes",
  "Hats",
  "Bags",
  "Accessories",
  "Toys",
  "Stuffed Animals",
  "Building Blocks",
  "Board Games",
  "Video Games",
  "Music",
  "Musical Instruments",
  "Books",
  "Library",
  "School",
  "Classroom",
  "Art Studio",
  "Craft Room",
  "Workshop",
  "Laboratory",
  "Office",
  "Bedroom",
  "Bathroom",
  "Living Room",
  "Kitchen Decor",
  "City",
  "Village",
  "Town",
  "Market",
  "Bakery Shop",
  "Flower Shop",
  "Toy Store",
  "Bookstore",
  "Museum",
  "Temple",
  "Shrine",
  "Ruins",
  "Bridge",
  "Tower",
  "Lighthouse Interior",
  "Treehouse",
  "Cabin",
  "Vehicles",
  "Cars",
  "Trucks",
  "Motorcycles",
  "Bicycles",
  "Trains",
  "Boats",
  "Ships",
  "Submarines",
  "Aircraft",
  "Hot Air Balloons",
  "Spaceships",
  "Steampunk",
  "Cyberpunk",
  "Cottagecore",
  "Dark Fantasy",
  "Dreams",
  "Nightmares",
  "Cozy",
  "Tiny Objects",
  "Miniature Worlds",
  "Patterns",
  "Stickers",
  "Emojis",
  "Pixel Art",
  "Doodles",
  "Stationery",
  "Camping",
  "Hiking",
  "Picnic",
  "Sports",
  "Camping Gear",
  "Fishing",
  "Magic Shop",
  "Potion Shop",
  "Clockwork",
  "Lanterns",
  "Windows",
  "Doors",
  "Keys",
  "Candles"
];

window.DOODLE_CREATIVE = [
  "Underwater Worlds",
  "Hidden Worlds",
  "Tiny Worlds",
  "Giant Worlds",
  "Lost Worlds",
  "Floating Worlds",
  "Dream Worlds",
  "Fantasy Worlds",
  "Magical Worlds",
  "Ancient Worlds",
  "Future Worlds",
  "Underground Worlds",
  "Sky Worlds",
  "Crystal Worlds",
  "Frozen Worlds",
  "Magical Forests",
  "Mysterious Forests",
  "Forgotten Places",
  "Hidden Places",
  "Cozy Places",
  "Peaceful Places",
  "Mysterious Places",
  "Ancient Places",
  "Abandoned Places",
  "Impossible Places",
  "Floating Places",
  "Animals with Jobs",
  "Animals on Vacation",
  "Animals Exploring",
  "Animals Celebrating",
  "Animals Relaxing",
  "Animals Building Things",
  "Animals Cooking",
  "Animals Traveling",
  "Animals Reading",
  "Animals Collecting Things",
  "Living Objects",
  "Objects with Faces",
  "Objects with Personalities",
  "Magical Objects",
  "Tiny Objects",
  "Giant Objects",
  "Forgotten Objects",
  "Floating Objects",
  "Glowing Objects",
  "Ancient Objects",
  "Food with Personalities",
  "Living Food",
  "Giant Food",
  "Tiny Food",
  "Magical Food",
  "Fantasy Food",
  "Colorful Food",
  "Sweet Worlds",
  "Cozy Kitchens",
  "Magical Recipes",
  "Fantasy Creatures",
  "Friendly Monsters",
  "Cute Monsters",
  "Mythical Beasts",
  "Forest Spirits",
  "Guardian Creatures",
  "Tiny Creatures",
  "Giant Creatures",
  "Flying Creatures",
  "Glowing Creatures",
  "Magical Plants",
  "Living Plants",
  "Giant Flowers",
  "Tiny Gardens",
  "Enchanted Gardens",
  "Mushroom Worlds",
  "Crystal Gardens",
  "Strange Plants",
  "Fantasy Forests",
  "Hidden Gardens",
  "Floating Islands",
  "Floating Castles",
  "Floating Gardens",
  "Sky Adventures",
  "Cloud Kingdoms",
  "Mountain Mysteries",
  "Deep Oceans",
  "Secret Caves",
  "Hidden Islands",
  "Lost Cities",
  "Space Adventures",
  "Alien Worlds",
  "Future Landscapes",
  "Robot Worlds",
  "Mechanical Creatures",
  "Clockwork Worlds",
  "Steampunk Adventures",
  "Cyber Worlds",
  "Cosmic Wonders",
  "Planet Explorations",
  "Cozy Corners",
  "Hidden Rooms",
  "Secret Doorways",
  "Mysterious Pathways",
  "Impossible Architecture",
  "Whimsical Buildings",
  "Tiny Houses",
  "Giant Furniture",
  "Living Architecture",
  "Magical Libraries",
  "Curious Workshops",
  "Enchanting Markets",
  "Fantasy Villages",
  "Peaceful Towns",
  "Busy Streets",
  "Quiet Landscapes",
  "Colorful Festivals",
  "Magical Celebrations",
  "Seasonal Magic",
  "Rainy Adventures",
  "Snowy Escapes",
  "Sunny Days",
  "Moonlit Nights",
  "Starry Skies",
  "Northern Lights",
  "Weather Wonders",
  "Changing Seasons",
  "Light & Shadows",
  "Reflections",
  "Silhouettes",
  "Treasure Hunts",
  "Lost Treasures",
  "Hidden Collections",
  "Curious Collections",
  "Ancient Relics",
  "Magical Artifacts",
  "Mystic Symbols",
  "Fantasy Maps",
  "Adventure Gear",
  "New Horizons",
  "Epic Journeys",
  "Everyday Magic",
  "Life in Miniature",
  "Worlds Within Worlds",
  "Secret Societies",
  "Hidden Civilizations",
  "Impossible Machines",
  "Curious Inventions",
  "Mechanical Wonders",
  "Living Machines",
  "Friendly Robots",
  "Future Relics",
  "Ancient Technology",
  "Magical Tools",
  "Enchanted Objects",
  "Cursed Objects",
  "Lucky Charms",
  "Powerful Artifacts",
  "Mystical Relics",
  "Strange Collections",
  "Treasures & Trinkets",
  "Curiosity Cabinets",
  "Cozy Moments",
  "Quiet Adventures",
  "Simple Pleasures",
  "Unexpected Friendships",
  "Peaceful Escapes",
  "Big Discoveries",
  "Hidden Beauty",
  "Everyday Wonders",
  "Small Mysteries",
  "Impossible Perspectives",
  "Gravity Gone Wrong",
  "Things That Shouldn't Fly",
  "Upside-Down Places",
  "Inside Out",
  "Beyond the Horizon",
  "Doors to Somewhere Else",
  "Windows into Another World",
  "The World Beneath",
  "The World Above",
  "A World in a Bottle",
  "Pocket Dimensions",
  "Mini Adventures",
  "Endless Staircases",
  "Living Shadows",
  "The Last Light",
  "First Day of Spring",
  "Golden Hour",
  "After the Rain",
  "Before the Storm"
];
