/* =====================================================================
   Doodle Spin — Listas de temas
   ---------------------------------------------------------------------
   Há DOIS modos, cada um com a sua própria lista:
     • CATEGORIES → temas amplos, por categoria.
     • CREATIVE   → prompts mais específicos e imaginativos.

   Edite à vontade! Regras simples:
     • Um tema por linha, entre aspas ("..."), terminado com vírgula.
     • Para ADICIONAR: acrescente uma nova linha na lista certa.
     • Para REMOVER: apague (ou comente com //) a linha.
   Depois é só recarregar a página.
   ===================================================================== */

window.DOODLE_CATEGORIES = [
  "Ocean",
  "Beach",
  "Coral Reef",
  "River",
  "Lake",
  "Pond",
  "Waterfall",
  "Swamp",
  "Marsh",
  "Island",
  "Harbor",
  "Lighthouse",
  "Pirate Cove",
  "Forest",
  "Jungle",
  "Rainforest",
  "Woodland",
  "Meadow",
  "Garden",
  "Botanical Garden",
  "Farm",
  "Orchard",
  "Vineyard",
  "Desert",
  "Oasis",
  "Canyon",
  "Mountains",
  "Volcano",
  "Cave",
  "Crystal Cave",
  "Arctic",
  "Antarctica",
  "Savanna",
  "Grasslands",
  "Sky",
  "Clouds",
  "Storm",
  "Rainbow",
  "Sunset",
  "Night Sky",
  "Space",
  "Moon",
  "Mars",
  "Planets",
  "Galaxy",
  "Constellations",
  "Nature",
  "Spring",
  "Summer",
  "Autumn",
  "Winter",
  "Weather",
  "Animals",
  "Pets",
  "Cats",
  "Dogs",
  "Birds",
  "Owls",
  "Butterflies",
  "Bees",
  "Insects",
  "Spiders",
  "Marine Life",
  "Fish",
  "Whales",
  "Sharks",
  "Octopus",
  "Turtles",
  "Reptiles",
  "Dinosaurs",
  "Dragons",
  "Fantasy Creatures",
  "Monsters",
  "Aliens",
  "Robots",
  "Magic",
  "Potions",
  "Spellbooks",
  "Witches",
  "Wizards",
  "Fairies",
  "Mermaids",
  "Unicorns",
  "Phoenix",
  "Mythology",
  "Fairy Tales",
  "Medieval",
  "Pirates",
  "Knights",
  "Castles",
  "Kingdoms",
  "Treasure",
  "Maps",
  "Halloween",
  "Christmas",
  "Easter",
  "Valentine's Day",
  "Carnival",
  "Circus",
  "Festival",
  "Birthday Party",
  "Food",
  "Desserts",
  "Candy",
  "Chocolate",
  "Ice Cream",
  "Cake",
  "Cookies",
  "Bread",
  "Pizza",
  "Pasta",
  "Burgers",
  "Sushi",
  "Fruits",
  "Vegetables",
  "Drinks",
  "Tea",
  "Coffee",
  "Bakery",
  "Kitchen",
  "Restaurant",
  "Tea Party",
  "Flowers",
  "Roses",
  "Sunflowers",
  "Tulips",
  "Cherry Blossoms",
  "Trees",
  "Leaves",
  "Mushrooms",
  "Cactus",
  "Succulents",
  "Vines",
  "Crystals",
  "Gems",
  "Rocks",
  "Shells",
  "Feathers",
  "Jewelry",
  "Crowns",
  "Fashion",
  "Clothing",
  "Shoes",
  "Hats",
  "Bags",
  "Accessories",
  "Toys",
  "Stuffed Animals",
  "Building Blocks",
  "Board Games",
  "Video Games",
  "Music",
  "Musical Instruments",
  "Books",
  "Library",
  "School",
  "Classroom",
  "Art Studio",
  "Craft Room",
  "Workshop",
  "Laboratory",
  "Office",
  "Bedroom",
  "Bathroom",
  "Living Room",
  "Kitchen Decor",
  "City",
  "Village",
  "Town",
  "Market",
  "Bakery Shop",
  "Flower Shop",
  "Toy Store",
  "Bookstore",
  "Museum",
  "Temple",
  "Shrine",
  "Ruins",
  "Bridge",
  "Tower",
  "Lighthouse Interior",
  "Treehouse",
  "Cabin",
  "Vehicles",
  "Cars",
  "Trucks",
  "Motorcycles",
  "Bicycles",
  "Trains",
  "Boats",
  "Ships",
  "Submarines",
  "Aircraft",
  "Hot Air Balloons",
  "Spaceships",
  "Steampunk",
  "Cyberpunk",
  "Cottagecore",
  "Dark Fantasy",
  "Dreams",
  "Nightmares",
  "Cozy",
  "Tiny Objects",
  "Miniature Worlds",
  "Patterns",
  "Stickers",
  "Emojis",
  "Pixel Art",
  "Doodles",
  "Stationery",
  "Camping",
  "Hiking",
  "Picnic",
  "Sports",
  "Camping Gear",
  "Fishing",
  "Magic Shop",
  "Potion Shop",
  "Clockwork",
  "Lanterns",
  "Windows",
  "Doors",
  "Keys",
  "Candles"
];

window.DOODLE_CREATIVE = [
  "Underwater Worlds",
  "Childhood Memories",
  "Myths & Legends",
  "Everyday Objects, Reimagined",
  "Nature vs. Machine",
  "Dreams & Nightmares",
  "Food & Feasts",
  "Travel & Wanderlust",
  "Emotions as Creatures",
  "Tiny Worlds",
  "Future Cities",
  "Seasons & Weather",
  "Animals with Jobs",
  "Abandoned Places",
  "Celebrations & Rituals",
  "Space & the Cosmos",
  "Underground & Hidden",
  "Portraits of Strangers",
  "Machines with Feelings",
  "Folklore & Fairy Tales",
  "Lost Civilizations",
  "Floating Islands",
  "Hidden Doorways",
  "Secret Gardens",
  "Imaginary Friends",
  "Impossible Architecture",
  "Living Toys",
  "Magical Libraries",
  "Forgotten Treasures",
  "Cozy Corners",
  "Night Creatures",
  "Daydreams",
  "Miniature Adventures",
  "Giant Objects",
  "Tiny Creatures",
  "Monster Friends",
  "Friendly Ghosts",
  "Living Shadows",
  "Things That Glow",
  "Worlds in a Bottle",
  "Nature Taking Over",
  "Wild Machines",
  "Fantasy Foods",
  "Magic & Potions",
  "Mysterious Forests",
  "Lost Kingdoms",
  "Hidden Villages",
  "Ancient Ruins",
  "Curious Inventions",
  "Clockwork Creations",
  "Floating Castles",
  "Secret Societies",
  "Pocket Dimensions",
  "Parallel Worlds",
  "Unexpected Heroes",
  "Villains on Vacation",
  "Animal Kingdoms",
  "Sky Adventures",
  "Ocean Mysteries",
  "Desert Secrets",
  "Crystal Caverns",
  "Frozen Wonders",
  "Volcanic Lands",
  "Jungle Explorers",
  "Haunted Houses",
  "Magical Marketplaces",
  "Fantasy Festivals",
  "Alien Life",
  "Robot Revolution",
  "The World Upside Down",
  "Impossible Creatures",
  "Living Plants",
  "Nature in the Future",
  "Cities of the Past",
  "Wild Weather",
  "Cozy Fantasy",
  "Dark Fantasy",
  "Light & Darkness",
  "Heroes & Sidekicks",
  "Hidden Monsters",
  "Magical Animals",
  "Curious Collections",
  "Doors to Another World",
  "Windows into the Unknown",
  "Time Travelers",
  "Lost & Found",
  "Before Humans",
  "After Humans",
  "Tiny Discoveries",
  "Everyday Magic",
  "Home, Reimagined",
  "Strange Traditions",
  "Festival of Lights",
  "Ancient Magic",
  "Future Relics",
  "Dream Jobs",
  "Impossible Sports",
  "Treasures of the Deep",
  "Sky Gardens",
  "Mystery & Wonder",
  "Worlds Beneath the Surface",
  "Hidden Histories",
  "Ancient Mysteries",
  "Forgotten Stories",
  "Impossible Landscapes",
  "Tiny Civilizations",
  "Giant Nature",
  "Nature in Bloom",
  "Wild Imaginations",
  "Life in the Clouds",
  "Life Underground",
  "Life Underwater",
  "Life on Another Planet",
  "Creatures of the Night",
  "Creatures of the Deep",
  "Creatures in Disguise",
  "Animals as Humans",
  "Plants with Personalities",
  "Objects Come Alive",
  "Food Comes Alive",
  "The Secret Life of Pets",
  "The Secret Life of Objects",
  "Fantasy Fashion",
  "Magical Clothing",
  "Curious Contraptions",
  "Mechanical Nature",
  "Organic Machines",
  "Natural Wonders",
  "Strange Ecosystems",
  "Fantasy Architecture",
  "Hidden Sanctuaries",
  "Lost Worlds Rediscovered",
  "The Last Sanctuary",
  "Floating Civilizations",
  "Future Wilderness",
  "Cities in Nature",
  "Nature Inside Cities",
  "Unexpected Places",
  "Mystical Landscapes",
  "Cozy Adventures",
  "Epic Discoveries",
  "Legends Reimagined",
  "History Reimagined",
  "The Future Reimagined",
  "Fantasy Cultures",
  "Imaginary Holidays",
  "Magical Traditions",
  "Everyday Heroes",
  "Unexpected Villains",
  "Impossible Friendships",
  "Fantasy Professions",
  "My Dream Home",
  "Dream Vacations",
  "Lost Maps",
  "Treasure & Mystery",
  "Adventures at Sea",
  "Life in the Trees",
  "Secret Hideouts",
  "The Edge of the World",
  "Sky Islands",
  "Worlds Above the Clouds",
  "Mysteries of Space",
  "Constellations Come Alive",
  "The Moon Reimagined",
  "Solar System Adventures",
  "Alien Cultures",
  "Robot Companions",
  "Future Transportation",
  "Steampunk Worlds",
  "Cyber Dreams",
  "Fantasy Technology",
  "Ancient Technology",
  "Magic Meets Science",
  "Dream Creatures",
  "Hybrid Animals",
  "Impossible Animals",
  "Legendary Places",
  "Mystical Waters",
  "Enchanted Seasons",
  "The Four Elements",
  "Fire & Ice",
  "Earth & Sky",
  "Light in the Darkness",
  "Shadow Worlds",
  "The Colorful Unknown",
  "Hidden Wonders",
  "Curious Discoveries",
  "Nature's Secrets",
  "Lost in Time",
  "Beyond Reality",
  "Unexpected Transformations",
  "The World of Giants",
  "The World of Miniatures",
  "Magic in Everyday Life",
  "Surreal Everyday Life",
  "Fantasy Sports",
  "Magical Music",
  "Living Art",
  "Worlds Yet to Be Discovered",
  "Beyond the Map",
  "Infinite Possibilities"
];
